export const ExceptionsFeedback = {
    UNEXPECTED_ERROR :{
        code: 'UNEXPECTED_ERROR',
        message: {
            en: 'UNEXPECTED_ERROR, please try again',
            ar : 'حدثت مكشلة برجاء المحاولة لاحقا'
        },
    }
}